spring.application.name=PokeAPI

spring.datasource.url=jdbc:postgresql://ep-quiet-flower-ac9p0e1p-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_hcJW8zdbFSx1
spring.datasource.driver-class-name=org.postgresql.Driver

server.servlet.session.persistent=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true